name: Automatus Sanity
on:
  pull_request:
    branches: [ master, 'stabilization*' ]
jobs:
  build-content:
    name: Build Content
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install Deps
        run: dnf install -y cmake make openscap-utils python3-pyyaml python3-jinja2 git python3-deepdiff python3-requests jq python3-pip
      - name: Install deps python
        run: pip install gitpython xmldiff
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout (CTF)
        uses: actions/checkout@v2
        with:
          repository: ComplianceAsCode/content-test-filtering
          path: ctf
      # https://github.com/actions/checkout/issues/766
      - name: Set git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Find forking point
        env:
          BASE_BRANCH: ${{ github.base_ref }}
        run: echo name=FORK_POINT::$(git merge-base origin/$BASE_BRANCH ${{ github.event.pull_request.head.sha }}) >> $GITHUB_OUTPUT"
        id: fork_point